### ISSUE TITLE
Provide a `finish` method on `IonWriter`s

### ISSUE THREAD

**Issue by sadderchris** [amazon-ion/ion-rust#713]
Right now, if I want to use an ion writer, I need to write code like this:

```rust
let mut sink = Vec::new();

// Scope needed so I can access `sink` after writing
{
    let mut writer = TextWriterBuilder::default().build(&mut sink)?;
    // do something with writer
    writer.flush()?;
}

// do something with `sink`
```

or

```rust
let mut sink = Vec::new();

                    
let mut writer = TextWriterBuilder::default().build(&mut sink)?;
// do something with writer...
writer.flush()?;
drop(writer);  // <-- Annoying that I have to remember to call drop here

// do something with `sink`
```

I've taken to defining a `finish` extension function in various places to make this more sensible

```rust
trait IonWriterExt {
    fn finish(self) -> IonResult<()>;
}

impl<W: IonWriter> IonWriterExt for W {
    fn finish(self) -> IonResult<()> {
        self.flush()
        // drops self
    }
} 
```

which allows me to write code like

```rust
let mut sink = Vec::new();

                    
let mut writer = TextWriterBuilder::default().build(&mut sink)?;
// do something with writer...
writer.finish()?;
// look ma, no drop!

// do something with `sink`
```

It would be nice if ion-rs supported this out of the box.

**Comment by zslayton** [comment]
Yeah, this is something I've stubbed my toe on too. I initially held off on it because I had (have!) hope that we'll add an API to re-use a writer's existing resources to start a new stream while avoiding reallocations. That's something I can easily add a separate method for though.

Should `finish()` return the output so you don't have to remember to pass a `&mut`?

In the meantime, the writer API has a `fn output(&self) -> &Self::Output` method (and a `mut_output`) that lets you get a handle to the output source without dropping the writer.

```rust
let mut sink = Vec::new();
let mut writer = TextWriterBuilder::default().build(&mut sink)?;
writer.write_symbol("foo")?;
writer.flush()?;
assert_eq!(writer.output(), "foo".as_bytes());
```

Not ideal, but often good enough for simple uses like unit tests.

**Comment by sadderchris** [comment]
> Should finish() return the output so you don't have to remember to pass a &mut?

Yes, that would be excellent.

> In the meantime, the writer API has a fn output(&self) -> &Self::Output method (and a mut_output) that lets you get a handle to the output source without dropping the writer.

This only really works if you don't need to pass along ownership of the sink, which we're often doing.  Like you said, good for unit tests, but impractical for real-world code.

**Comment by desaikd** [comment]
Completed with #720
